# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  # 1. 트랙볼 마우스 본체용 (기존 설정)
  - board: seeeduino_xiao_ble
    shield: AdeptBLE
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

# 2. Holyiot 동글 수신기용 (본체 오버레이 무시 및 무력화 명령어 추가)
  - board: nrf52840dongle_nrf52840
    shield: AdeptBLE
    cmake-args: -DSHIELD_AdeptBLE_overlay_DTS_UNUSED=y -DCONFIG_PMW3610=n
